
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 07 00:25:17 CET 2007
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class AnalizaSym {
  /* terminals */
  public static final int AND = 3;
  public static final int EOF = 0;
  public static final int UNOT = 8;
  public static final int error = 1;
  public static final int RPAREN = 7;
  public static final int IDENTIFIER = 2;
  public static final int NOT = 4;
  public static final int LPAREN = 6;
  public static final int OR = 5;
}

