
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 07 13:00:42 CET 2007
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 5;
  public static final int UMINUS = 8;
  public static final int EOF = 0;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int RPAREN = 4;
  public static final int NOT = 7;
  public static final int LPAREN = 3;
  public static final int OR = 6;
}

